Repository ASAP-Side/iOS-aljo, pull requests merged in 2024-03, with the labels that each got.

#63 [FEATURE] ASSlider 타입 구현
  aljo/Projects/UserInterface/ASAPKit/Demo/Sources/StoryBook/ComponentScene/Sliders/ASSliderDemoController.swift
  aljo/Projects/UserInterface/ASAPKit/Demo/Sources/StoryBook/Model/DemoCategory.swift
  aljo/Projects/UserInterface/ASAPKit/Resources/Icon/Symbols.xcassets/sound.imageset/Contents.json
  aljo/Projects/UserInterface/ASAPKit/Resources/Icon/Symbols.xcassets/sound.imageset/sound_mute.svg
  aljo/Projects/UserInterface/ASAPKit/Resources/Icon/Symbols.xcassets/sound_mute.imageset/Contents.json
  aljo/Projects/UserInterface/ASAPKit/Resources/Icon/Symbols.xcassets/sound_mute.imageset/sound_mute.svg
  aljo/Projects/UserInterface/ASAPKit/Sources/Components/ASButton/Configuration + Style.swift
  aljo/Projects/UserInterface/ASAPKit/Sources/Components/ASButton/RoundButton.swift
  aljo/Projects/UserInterface/ASAPKit/Sources/Components/ASSlider/ASSlider.swift
  aljo/Projects/UserInterface/ASAPKit/Sources/Configurations/Icon + Extension.swift
Labels: 🎨 UI, ✨ Feature

#62 [FEATURE] ASStepper 구현
  aljo/Projects/UserInterface/ASAPKit/Demo/Sources/StoryBook/ComponentScene/ASStepper/ASStepperDemoController.swift
  aljo/Projects/UserInterface/ASAPKit/Demo/Sources/StoryBook/ComponentScene/TextView/ASTextViewDemoController.swift
  aljo/Projects/UserInterface/ASAPKit/Demo/Sources/StoryBook/FoundationScene/ColorViewController/ColorCell.swift
  aljo/Projects/UserInterface/ASAPKit/Demo/Sources/StoryBook/FoundationScene/ColorViewController/ColorStoryViewController.swift
  aljo/Projects/UserInterface/ASAPKit/Demo/Sources/StoryBook/FoundationScene/FontViewController/FontCell.swift
  aljo/Projects/UserInterface/ASAPKit/Demo/Sources/StoryBook/FoundationScene/FontViewController/FontHeaderView.swift
  aljo/Projects/UserInterface/ASAPKit/Demo/Sources/StoryBook/FoundationScene/FontViewController/FontStoryViewController.swift
  aljo/Projects/UserInterface/ASAPKit/Demo/Sources/StoryBook/FoundationScene/IconStoryViewController/IconCell.swift
  aljo/Projects/UserInterface/ASAPKit/Demo/Sources/StoryBook/FoundationScene/IconStoryViewController/IconStoryViewController.swift
  aljo/Projects/UserInterface/ASAPKit/Demo/Sources/StoryBook/Model/ColorModel.swift
  aljo/Projects/UserInterface/ASAPKit/Demo/Sources/StoryBook/Model/DemoCategory.swift
  aljo/Projects/UserInterface/ASAPKit/Demo/Sources/StoryBook/RootScene/StoryRootViewController.swift
  aljo/Projects/UserInterface/ASAPKit/Demo/Sources/StoryBook/RootScene/Views/DemoCategoryCell.swift
  aljo/Projects/UserInterface/ASAPKit/Demo/Sources/Utils/NavigationController.swift
  aljo/Projects/UserInterface/ASAPKit/Resources/Color/Basic.xcassets/Black01.colorset/Contents.json
  aljo/Projects/UserInterface/ASAPKit/Resources/Color/Basic.xcassets/Black02.colorset/Contents.json
  aljo/Projects/UserInterface/ASAPKit/Resources/Color/Basic.xcassets/Black03.colorset/Contents.json
  aljo/Projects/UserInterface/ASAPKit/Resources/Color/Basic.xcassets/Black04.colorset/Contents.json
  aljo/Projects/UserInterface/ASAPKit/Resources/Icon/Symbols.xcassets/minus.imageset/Contents.json
  aljo/Projects/UserInterface/ASAPKit/Resources/Icon/Symbols.xcassets/plus.imageset/Contents.json
  aljo/Projects/UserInterface/ASAPKit/Sources/Components/ASButton/Configuration + Style.swift
  aljo/Projects/UserInterface/ASAPKit/Sources/Components/ASRectButton/ASRectButton.swift
  aljo/Projects/UserInterface/ASAPKit/Sources/Components/ASStepper/ASStepper+Rx.swift
  aljo/Projects/UserInterface/ASAPKit/Sources/Components/ASStepper/ASStepper.swift
  aljo/Projects/UserInterface/ASAPKit/Sources/Components/ASTextField/ASBorderHighlightTextField.swift
  aljo/Projects/UserInterface/ASAPKit/Sources/Components/ASTextField/ASUnderBarTextField.swift
  aljo/Projects/UserInterface/ASAPKit/Sources/Components/ASTextView.swift
  aljo/Projects/UserInterface/ASAPKit/Sources/Configurations/Color + Extension.swift
Labels: 🎨 UI, ✨ Feature

#67 [FIX] ASRectButton 메모리 누수 수정
  aljo/Projects/UserInterface/ASAPKit/Sources/Components/ASRectButton/ASRectButton.swift
Labels: 🐞 Fix

#69 [FIX] ASUnderBarText 버그 수정
  aljo/Projects/UserInterface/ASAPKit/Sources/Components/ASTextField/ASTextField+Rx/ASUnderBarTextField+Rx.swift
  aljo/Projects/UserInterface/ASAPKit/Sources/Components/ASTextField/ASUnderBarTextField.swift
Labels: 🐞 Fix

#70 [FIX] Round Button 메모리 누수 버그 수정
  aljo/Projects/UserInterface/ASAPKit/Demo/Sources/StoryBook/ComponentScene/ASRectButton/ASRectButtonDemoController.swift
  aljo/Projects/UserInterface/ASAPKit/Demo/Sources/StoryBook/ComponentScene/ASStepper/ASStepperDemoController.swift
  aljo/Projects/UserInterface/ASAPKit/Demo/Sources/StoryBook/ComponentScene/ASTextField/ASTextFieldDemoController.swift
  aljo/Projects/UserInterface/ASAPKit/Demo/Sources/StoryBook/ComponentScene/Buttons/ASRectButtonDemoController.swift
  aljo/Projects/UserInterface/ASAPKit/Demo/Sources/StoryBook/ComponentScene/Buttons/ASRoundButtonDemoController.swift
  aljo/Projects/UserInterface/ASAPKit/Demo/Sources/StoryBook/ComponentScene/Slider/ASSliderDemoController.swift
  aljo/Projects/UserInterface/ASAPKit/Demo/Sources/StoryBook/ComponentScene/Sliders/ASSliderDemoController.swift
  aljo/Projects/UserInterface/ASAPKit/Demo/Sources/StoryBook/ComponentScene/Stepper/ASStepperDemoController.swift
  aljo/Projects/UserInterface/ASAPKit/Demo/Sources/StoryBook/ComponentScene/TextField/ASTextFieldDemoController.swift
  aljo/Projects/UserInterface/ASAPKit/Demo/Sources/StoryBook/ComponentScene/TextView/ASTextViewDemoController.swift
  aljo/Projects/UserInterface/ASAPKit/Demo/Sources/StoryBook/Model/DemoCategory.swift
  aljo/Projects/UserInterface/ASAPKit/Sources/Components/ASButton/RoundButton.swift
  aljo/Projects/UserInterface/ASAPKit/Sources/Components/ASTextField/ASUnderBarTextField.swift
Labels: 🐞 Fix

#71 [FEATURE] ASListView 구현
  aljo/Projects/UserInterface/ASAPKit/Demo/Sources/StoryBook/ContainerScene/ASListViewDemoController.swift
  aljo/Projects/UserInterface/ASAPKit/Demo/Sources/StoryBook/Model/DemoCategory.swift
  aljo/Projects/UserInterface/ASAPKit/Sources/Components/ASStepper/ASStepper.swift
  aljo/Projects/UserInterface/ASAPKit/Sources/Containers/ASListView/ASListView.swift
  aljo/Projects/UserInterface/ASAPKit/Sources/Containers/ASListView/HeaderBox.swift
Labels: ✨ Feature

#75 [REFACTOR] ASTextField RxCocoa 의존성 제거
  aljo/Projects/UserInterface/ASAPKit/Demo/Sources/StoryBook/ComponentScene/TextField/ASTextFieldDemoController.swift
  aljo/Projects/UserInterface/ASAPKit/Sources/Components/ASTextField/ASBorderHighlightTextField.swift
  aljo/Projects/UserInterface/ASAPKit/Sources/Components/ASTextField/ASUnderBarTextField.swift
Labels: 🔨 Refactor

#76 [REFACTOR] TextView, Stepper 바인딩 메서드 삭제
  aljo/Projects/UserInterface/ASAPKit/Demo/Sources/StoryBook/ComponentScene/Stepper/ASStepperDemoController.swift
  aljo/Projects/UserInterface/ASAPKit/Demo/Sources/StoryBook/ComponentScene/TextView/ASTextViewDemoController.swift
  aljo/Projects/UserInterface/ASAPKit/Sources/Components/ASStepper/ASStepper.swift
  aljo/Projects/UserInterface/ASAPKit/Sources/Components/ASTextView/ASTextView.swift
Labels: 🔨 Refactor

#78 [FEATURE] ASBottomSheet
  aljo/Projects/UserInterface/ASAPKit/Demo/Sources/StoryBook/ContainerScene/ASListViewDemoController.swift
  aljo/Projects/UserInterface/ASAPKit/Demo/Sources/StoryBook/ControllerScene/ASBottomSheet/ASBottomSheetDemoController.swift
  aljo/Projects/UserInterface/ASAPKit/Demo/Sources/StoryBook/ControllerScene/ASBottomSheet/BottomSheetListViewController.swift
  aljo/Projects/UserInterface/ASAPKit/Demo/Sources/StoryBook/ControllerScene/ASBottomSheet/BottomSheetPasswordViewController.swift
  aljo/Projects/UserInterface/ASAPKit/Demo/Sources/StoryBook/Model/DemoCategory.swift
  aljo/Projects/UserInterface/ASAPKit/Sources/Components/ASTextField/ASUnderBarTextField.swift
  aljo/Projects/UserInterface/ASAPKit/Sources/Controllers/ASBottomSheet/ASBottomSheetAnimator.swift
  aljo/Projects/UserInterface/ASAPKit/Sources/Controllers/ASBottomSheet/ASBottomSheetController.swift
  aljo/Projects/UserInterface/ASAPKit/Sources/Controllers/ASBottomSheet/ASBottomSheetDetent.swift
  aljo/Projects/UserInterface/ASAPKit/Sources/Controllers/ASBottomSheet/ASBottomSheetPresentationController.swift
  aljo/Projects/UserInterface/ASAPKit/Sources/Controllers/ASBottomSheet/ASBottomSheetTransitionDelegate.swift
Labels: ✨ Feature

#82 [FEATURE] ASImagePicker 타입 구현
  aljo/Projects/UserInterface/ASAPKit/Demo/Sources/StoryBook/ControllerScene/ASImagePickerDemoController.swift
  aljo/Projects/UserInterface/ASAPKit/Demo/Sources/StoryBook/Model/DemoCategory.swift
  aljo/Projects/UserInterface/ASAPKit/Sources/Components/ASButton/Configuration + Style.swift
  aljo/Projects/UserInterface/ASAPKit/Sources/Controllers/ASImagePickerViewController/ASImagePickerViewController.swift
  aljo/Projects/UserInterface/ASAPKit/Sources/Controllers/ASImagePickerViewController/AssetImageGridCell.swift
Labels: 🎨 UI, ✨ Feature
