Repository ASAP-Side/iOS-aljo, pull requests merged in 2024-02, with the labels that each got.

#39 [FEATURE] AJCoreData 모듈 구현
  aljo/Plugin/AljoPlugin/ProjectDescriptionHelpers/ModulePaths.swift
  aljo/Projects/Core/AJCoreData/Implementation/CoreDataWorker.swift
  aljo/Projects/Core/AJCoreData/Implementation/DefaultCoreDataStorage.swift
  aljo/Projects/Core/AJCoreData/Implementation/Resources/ALJO_MODEL.xcdatamodeld/ALJO_MODEL.xcdatamodel/contents
  aljo/Projects/Core/AJCoreData/Interface/CoreDataError.swift
  aljo/Projects/Core/AJCoreData/Interface/CoreDataStorage.swift
  aljo/Projects/Core/AJCoreData/Interface/CoreDataWorkerProtocol.swift
  aljo/Projects/Core/AJCoreData/Interface/ManagedObjectConvertible.swift
  aljo/Projects/Core/AJCoreData/Interface/ManagedObjectProtocol.swift
  aljo/Projects/Core/AJCoreData/Project.swift
  aljo/Projects/Core/AJCoreData/Testing/CoreDataStorageTestError.swift
  aljo/Projects/Core/AJCoreData/Testing/DummyTest.swift
  aljo/Projects/Core/AJCoreData/Testing/Resources/DUMMYTEST/DUMMYTEST.xcdatamodeld/DUMMYTEST.xcdatamodel/contents
  aljo/Projects/Core/AJCoreData/Testing/StubCoreDataWorker.swift
  aljo/Projects/Core/AJCoreData/Tests/DefaultCoreDataStorageTests.swift
  aljo/Tuist/ProjectDescriptionHelpers/Target + Templates.swift
Labels: ✅ Test, ✨ Feature

#38 [Feature] KeyChain 모듈 생성
  aljo/Plugin/AljoPlugin/ProjectDescriptionHelpers/ModulePaths.swift
  aljo/Projects/App/Project.swift
  aljo/Projects/Core/AJKeychain/Implementation/DefaultKeyChainStorage.swift
  aljo/Projects/Core/AJKeychain/Interface/KeyChainError.swift
  aljo/Projects/Core/AJKeychain/Interface/KeyChainStorage.swift
  aljo/Projects/Core/AJKeychain/Project.swift
  aljo/Scripts/.swiftlint.yml
  aljo/Scripts/SwiftLintRunScript.sh
  aljo/Tuist/ProjectDescriptionHelpers/Target + Templates.swift
  aljo/Tuist/ProjectDescriptionHelpers/TargetScript + Templates.swift
Labels: ✅ Test, ✨ Feature

#50 [CONFIG] Tuist 미흡한 설정 추가하기
  aljo/Plugin/AljoPlugin/ProjectDescriptionHelpers/TargetDependency + ExternalDependency.swift
  aljo/Plugin/TemplatePlugin/Templates/Demo/AppInfoPlist.stencil
  aljo/Plugin/TemplatePlugin/Templates/Demo/Demo.swift
  aljo/Plugin/TemplatePlugin/Templates/Module/Module.swift
  aljo/Plugin/TemplatePlugin/Templates/Module/Project.stencil
  aljo/Plugin/TemplatePlugin/Templates/Tests/Tests.swift
  aljo/Plugin/TemplatePlugin/Templates/uFeature/uFeature.swift
  aljo/Projects/Core/AJCoreData/Project.swift
  aljo/Projects/Core/AJNetwork/Project.swift
  aljo/Tuist/ProjectDescriptionHelpers/Target + Templates.swift
Labels: ⚙ Setting

#51 [CONFIG] Tuist Design System 파일 생성 및 Demo 생성
  aljo/Plugin/AljoPlugin/ProjectDescriptionHelpers/ModulePaths.swift
  aljo/Plugin/TemplatePlugin/Templates/Demo/Demo.swift
  aljo/Plugin/TemplatePlugin/Templates/Demo/SceneDelegate.stencil
  aljo/Plugin/TemplatePlugin/Templates/uFeature/uFeature.swift
  aljo/Projects/UserInterface/ASAPKit/Demo/AppDelegate.swift
  aljo/Projects/UserInterface/ASAPKit/Demo/Resources/LaunchScreen.storyboard
  aljo/Projects/UserInterface/ASAPKit/Demo/SceneDelegate.swift
  aljo/Projects/UserInterface/ASAPKit/Demo/Sources/AppDelegate.swift
  aljo/Projects/UserInterface/ASAPKit/Demo/Sources/StoryBook/Model/DemoCategory.swift
  aljo/Projects/UserInterface/ASAPKit/Demo/Sources/StoryBook/RootScene/StoryRootViewController.swift
  aljo/Projects/UserInterface/ASAPKit/Demo/Sources/StoryBook/RootScene/Views/DemoCategoryCell.swift
  aljo/Projects/UserInterface/ASAPKit/Implementation/Implementation.swift
  aljo/Projects/UserInterface/ASAPKit/Interface/Interface.swift
  aljo/Projects/UserInterface/ASAPKit/Project.swift
  aljo/Projects/UserInterface/ASAPKit/Resources/Color/Basic.xcassets/Body01.colorset/Contents.json
  aljo/Projects/UserInterface/ASAPKit/Resources/Color/Basic.xcassets/Body02.colorset/Contents.json
  aljo/Projects/UserInterface/ASAPKit/Resources/Color/Basic.xcassets/Contents.json
  aljo/Projects/UserInterface/ASAPKit/Resources/Color/Basic.xcassets/Disable.colorset/Contents.json
  aljo/Projects/UserInterface/ASAPKit/Resources/Color/Basic.xcassets/Title.colorset/Contents.json
  aljo/Projects/UserInterface/ASAPKit/Resources/Color/Grey.xcassets/Contents.json
  aljo/Projects/UserInterface/ASAPKit/Resources/Color/Grey.xcassets/Grey01.colorset/Contents.json
  aljo/Projects/UserInterface/ASAPKit/Resources/Color/Grey.xcassets/Grey02.colorset/Contents.json
  aljo/Projects/UserInterface/ASAPKit/Resources/Color/Grey.xcassets/Grey03.colorset/Contents.json
  aljo/Projects/UserInterface/ASAPKit/Resources/Color/Grey.xcassets/Grey04.colorset/Contents.json
  aljo/Projects/UserInterface/ASAPKit/Resources/Color/Grey.xcassets/White.colorset/Contents.json
  aljo/Projects/UserInterface/ASAPKit/Resources/Color/Primary.xcassets/Contents.json
  aljo/Projects/UserInterface/ASAPKit/Resources/Color/Primary.xcassets/Red01.colorset/Contents.json
  aljo/Projects/UserInterface/ASAPKit/Resources/Color/Primary.xcassets/Red02.colorset/Contents.json
  aljo/Projects/UserInterface/ASAPKit/Resources/Color/System.xcassets/Blue.colorset/Contents.json
  aljo/Projects/UserInterface/ASAPKit/Resources/Color/System.xcassets/Contents.json
  aljo/Projects/UserInterface/ASAPKit/Resources/Color/System.xcassets/Green.colorset/Contents.json
  aljo/Projects/UserInterface/ASAPKit/Resources/Color/System.xcassets/Red.colorset/Contents.json
  aljo/Projects/UserInterface/ASAPKit/Resources/Font/Pretendard-Black.otf
  aljo/Projects/UserInterface/ASAPKit/Resources/Font/Pretendard-Bold.otf
  aljo/Projects/UserInterface/ASAPKit/Resources/Font/Pretendard-ExtraBold.otf
  aljo/Projects/UserInterface/ASAPKit/Resources/Font/Pretendard-ExtraLight.otf
  aljo/Projects/UserInterface/ASAPKit/Resources/Font/Pretendard-Light.otf
  aljo/Projects/UserInterface/ASAPKit/Resources/Font/Pretendard-Medium.otf
  aljo/Projects/UserInterface/ASAPKit/Resources/Font/Pretendard-Regular.otf
  aljo/Projects/UserInterface/ASAPKit/Resources/Font/Pretendard-SemiBold.otf
  aljo/Projects/UserInterface/ASAPKit/Resources/Font/Pretendard-Thin.otf
  aljo/Projects/UserInterface/ASAPKit/Sources/ASTextView.swift
  aljo/Projects/UserInterface/ASAPKit/Sources/Configurations/Font + Extension.swift
  aljo/Projects/UserInterface/ASAPKit/Testing/Testing.swift
  aljo/Tuist/ProjectDescriptionHelpers/Project + Templates.swift
  aljo/Tuist/ProjectDescriptionHelpers/Target + Templates.swift
Labels: 🎨 UI, ⚙ Setting

#54 [FEATURE] ASTextField 구현
  aljo/Plugin/AljoPlugin/ProjectDescriptionHelpers/TargetDependency + ExternalDependency.swift
  aljo/Projects/UserInterface/ASAPKit/Project.swift
  aljo/Projects/UserInterface/ASAPKit/Resources/Icon/Xmark.xcassets/remove_black.imageset/Contents.json
  aljo/Projects/UserInterface/ASAPKit/Resources/Icon/Xmark.xcassets/remove_black.imageset/xmark.svg
  aljo/Projects/UserInterface/ASAPKit/Resources/Icon/Xmark.xcassets/remove_circle.imageset/Contents.json
  aljo/Projects/UserInterface/ASAPKit/Resources/Icon/Xmark.xcassets/remove_circle.imageset/xmark_circle_fill.svg
  aljo/Projects/UserInterface/ASAPKit/Sources/Components/ASTextField/ASBorderHighlightTextField.swift
  aljo/Projects/UserInterface/ASAPKit/Sources/Components/ASTextField/ASTextField+Rx/ASUnderBarTextField+Rx.swift
  aljo/Projects/UserInterface/ASAPKit/Sources/Components/ASTextField/ASUnderBarTextField.swift
  aljo/Projects/UserInterface/ASAPKit/Sources/Configurations/Icon + Extension.swift
Labels: 🎨 UI

#57 [FEATURE] 데모 컴포넌트 구현
  aljo/Plugin/AljoPlugin/ProjectDescriptionHelpers/TargetDependency + ExternalDependency.swift
  aljo/Projects/UserInterface/ASAPKit/Demo/Resources/Assets.xcassets/AppIcon.appiconset/1024.png
  aljo/Projects/UserInterface/ASAPKit/Demo/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  aljo/Projects/UserInterface/ASAPKit/Demo/Resources/Assets.xcassets/Contents.json
  aljo/Projects/UserInterface/ASAPKit/Demo/Sources/StoryBook/ComponentScene/ComponentViewController.swift
  aljo/Projects/UserInterface/ASAPKit/Demo/Sources/StoryBook/ComponentScene/TextView/ASTextViewDemoController.swift
  aljo/Projects/UserInterface/ASAPKit/Demo/Sources/StoryBook/Model/DemoCategory.swift
  aljo/Projects/UserInterface/ASAPKit/Demo/Sources/StoryBook/RootScene/StoryRootViewController.swift
  aljo/Projects/UserInterface/ASAPKit/Project.swift
  aljo/Projects/UserInterface/ASAPKit/Sources/ASTextView.swift
  aljo/Projects/UserInterface/ASAPKit/Sources/Components/ASTextView.swift
Labels: 🎨 UI, ✨ Feature

#55 [FEATURE] ASTextView 구현
  aljo/Plugin/AljoPlugin/ProjectDescriptionHelpers/TargetDependency + ExternalDependency.swift
  aljo/Projects/UserInterface/ASAPKit/Demo/Sources/StoryBook/RootScene/StoryRootViewController.swift
  aljo/Projects/UserInterface/ASAPKit/Sources/Components/ASTextView.swift
Labels: 🎨 UI, 📃 Docs

#60 [FEATURE] Round Button 구현
  aljo/Projects/UserInterface/ASAPKit/Demo/Sources/StoryBook/ComponentScene/Buttons/ASRoundButtonDemoController.swift
  aljo/Projects/UserInterface/ASAPKit/Demo/Sources/StoryBook/FoundationScene/FontViewController/FontCell.swift
  aljo/Projects/UserInterface/ASAPKit/Demo/Sources/StoryBook/FoundationScene/FontViewController/FontStoryViewController.swift
  aljo/Projects/UserInterface/ASAPKit/Demo/Sources/StoryBook/Model/ColorModel.swift
  aljo/Projects/UserInterface/ASAPKit/Demo/Sources/StoryBook/Model/DemoCategory.swift
  aljo/Projects/UserInterface/ASAPKit/Demo/Sources/StoryBook/RootScene/StoryRootViewController.swift
  aljo/Projects/UserInterface/ASAPKit/Demo/Sources/StoryBook/RootScene/Views/DemoCategoryCell.swift
  aljo/Projects/UserInterface/ASAPKit/Demo/Sources/Utils/Reusable + Extension.swift
  aljo/Projects/UserInterface/ASAPKit/Demo/Sources/Utils/UIColor + Extensions.swift
  aljo/Projects/UserInterface/ASAPKit/Demo/Sources/Utils/UILabel + Extension.swift
  aljo/Projects/UserInterface/ASAPKit/Resources/Icon/Symbols.xcassets/check.imageset/18_nomal.svg
  aljo/Projects/UserInterface/ASAPKit/Resources/Icon/Symbols.xcassets/check.imageset/Contents.json
  aljo/Projects/UserInterface/ASAPKit/Resources/Icon/Symbols.xcassets/checkSmall.imageset/Contents.json
  aljo/Projects/UserInterface/ASAPKit/Resources/Icon/Symbols.xcassets/checkSmall.imageset/check_small.svg
  aljo/Projects/UserInterface/ASAPKit/Sources/Components/ASButton/Configuration + Style.swift
  aljo/Projects/UserInterface/ASAPKit/Sources/Components/ASButton/RoundButton.swift
  aljo/Projects/UserInterface/ASAPKit/Sources/Configurations/Icon + Extension.swift
  aljo/Scripts/.swiftlint.yml
Labels: 🎨 UI, ✨ Feature
