Repository ASAP-Side/iOS-aljo, pull requests merged in 2024-04, with the labels that each got.

#87 [CONFIG] AppSigning 수정
  .gitignore
  aljo/Derived/.fl25C0AF36
  aljo/Derived/signing.keychain
  aljo/Plugin/EnvironmentPlugin/ProjectDescriptionHelpers/ProjectEnvironment.swift
  aljo/Tuist/master.key
Labels: ⚙ Setting

#89 [CONFIG] Swinject 의존성 추가
  aljo/Plugin/AljoPlugin/ProjectDescriptionHelpers/TargetDependency + ExternalDependency.swift
  aljo/Projects/Core/AJCoreData/Implementation/AJCoreDataStorage.swift
  aljo/Projects/Core/AJCoreData/Implementation/AJCoreDataWorker.swift
  aljo/Projects/Core/AJCoreData/Implementation/Assembly/AJCoreDataAssembly.swift
  aljo/Projects/Core/AJCoreData/Interface/CoreDataWorker.swift
  aljo/Projects/Core/AJCoreData/Project.swift
  aljo/Projects/Core/AJCoreData/Testing/StubCoreDataWorker.swift
  aljo/Projects/Core/AJKeychain/Implementation/AJKeyChainStorage.swift
  aljo/Projects/Core/AJKeychain/Implementation/Assembly/AJKeychainAssembly.swift
  aljo/Projects/Core/AJKeychain/Interface/KeyChainStorage.swift
  aljo/Projects/Core/AJKeychain/Project.swift
  aljo/Projects/Core/AJNetwork/Implementation/AJNetworkProvider.swift
  aljo/Projects/Core/AJNetwork/Implementation/Assembly/AJNetworkAssembly.swift
  aljo/Projects/Core/AJNetwork/Interface/NetworkProvider.swift
  aljo/Projects/Core/AJNetwork/Interface/NetworkRouter.swift
  aljo/Projects/Core/AJNetwork/Interface/Provider.swift
  aljo/Projects/Core/AJNetwork/Project.swift
  aljo/Projects/Core/AJNetwork/Testing/DummyRouter.swift
  aljo/Tuist/Dependencies.swift
Labels: ✨ Feature, ⚙ Setting

#91 [CONFIG] 디자인 시스템 수정 및 추가
  aljo/Projects/UserInterface/ASAPKit/Resources/Color/System.xcassets/Yellow.colorset/Contents.json
  aljo/Projects/UserInterface/ASAPKit/Resources/Icon/Profile.xcassets/Contents.json
  aljo/Projects/UserInterface/ASAPKit/Resources/Icon/Profile.xcassets/camera_button.imageset/Contents.json
  aljo/Projects/UserInterface/ASAPKit/Resources/Icon/Profile.xcassets/camera_button.imageset/camera_button.svg
  aljo/Projects/UserInterface/ASAPKit/Resources/Icon/Profile.xcassets/profile_default.imageset/Contents.json
  aljo/Projects/UserInterface/ASAPKit/Resources/Icon/Profile.xcassets/profile_default.imageset/profile.svg
  aljo/Projects/UserInterface/ASAPKit/Resources/Icon/Symbols.xcassets/check_small.imageset/Contents.json
  aljo/Projects/UserInterface/ASAPKit/Resources/Icon/Symbols.xcassets/check_small.imageset/check_small.svg
  aljo/Projects/UserInterface/ASAPKit/Sources/Configurations/Color + Extension.swift
  aljo/Projects/UserInterface/ASAPKit/Sources/Configurations/Icon + Extension.swift
Labels: 🎨 UI, ⚙ Setting
